
services:
  # QGroundControl - Ground Control Station
  qgc:
    build:
      context: .
      dockerfile: docker/qgc5.dockerfile
    image: qgc5-vtol:latest

    restart: no
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
    volumes:
      - ${HOME}/.Xauthority:/home/qgc/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/sim2sim:/home/qgc/ulgs/
      - /dev/input:/dev/input
    command: qgc
    network_mode: bridge
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  # ROS2 Workspace - Neural control and inference
  ros2:
    build:
      context: .
      dockerfile: docker/ros2.dockerfile
      args:
        LATETST: "true"
    image: ros2-vtol:latest

    restart: no
    privileged: true
    working_dir: /home/ros/ros2_ws
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
      - ROS_DISTRO=humble
      - INFER_WORKSPACE=/home/ros/ros2_ws
    volumes:
      - ${HOME}/.Xauthority:/home/ros/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src:/home/ros/ros2_ws/src
      - ./scripts:/home/ros/ros2_ws/scripts
    command: tail -f /dev/null
    stdin_open: true
    tty: true
    network_mode: bridge
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

  # PX4 Gazebo Simulator
  px4:
    build:
      context: .
      dockerfile: docker/px4-gazebo.dockerfile
    image: px4-gazebo-harmonic-vtol:v1

    restart: no
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: tail -f /dev/null
    stdin_open: true
    tty: true
    network_mode: bridge
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
